[platformio]
src_dir = agro_vault

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.15
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
